# Generated by Django 5.2.2 on 2025-06-05 02:36

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Url",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("original_url", models.URLField(unique=True)),
                ("short_url", models.SlugField(blank=True, unique=True)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
